### ISSUE TITLE
[수정] 프로젝트 구조 수정

### ISSUE THREAD

**Issue by Eeap** [Terraform-Canvas/front-end#12]
## 🚀 Feature Request

- [ ] App.vue 페이지마다 reuse하기 위해 수정
- [ ] 로그인 임시 라우팅 추가

## 📎 Additional context

필요하다면 상태 관리도 추가
@FacerAin refactor/project-structure -> dev -> main 순으로 해서 프로젝트 구조 병합할 예정입니다 :)

**Comment by FacerAin** [comment]
말씀해주신대로 기능별로 Common(ex. Header, Button, Footer), Nodes 등으로 컴포넌트 정리해서 재사용성 측면 고려하여 작업해보겠습니다😊  

- Using presentation and container pattern for vuejs
- Using context management system
- Refer to vue template project structure [[link](https://github.com/PanJiaChen/vue-admin-template)]
