### ISSUE TITLE
[버그] node 클릭 시 rightdrawer의 활성화 이슈

### ISSUE THREAD

**Issue by Eeap** [Terraform-Canvas/front-end#14]
## 🐛 Bug Report

node 컴포넌트를 만들고 해당 내용을 넣기 위해 클릭 시 rightdrawer가 뜨지 않는 오류가 존재

## 🔬 How To Reproduce

전체적인 플로우 수정이 필요

## 📎 Additional context
아무래도 컴포넌트 간 부모 자식이 잘못돼서 데이터를 못받아서 그런것 같아서 flow를 잘 수정하거나 상태 관리가 필요할 것 같아요
@FacerAin

**Comment by FacerAin** [comment]
`@/views/dashboard/index.vue`에서 `handleRightDrawer`라는 이벤트 리스너를 통해 `drawer` 값으로 **표시 여부를 결정**하는데,
정작 drawer 객체는 `@/layouts/index.vue`에 위치하여 **값을 정상적으로 받아오지 못하여 발생하는 문제** 같습니다!

해결하는 방법으로 **전역 상태 관리**를 수행하거나, rightdrawer와 handleRightDrawer를 **적절히 함께 위치**시키는 방법이 있을 것 같습니다!
