### ISSUE TITLE
[수정] Appbar logo 변경

### ISSUE THREAD

**Issue by FacerAin** [Terraform-Canvas/front-end#17]
## 🚀 Feature Request
- 현재 상단에 Appbar에 서비스 logo 존재
- 하지만 크기가 작고, 레이아웃이 잘 배치되어 있지 않음
- 따라서 적절한 logo의 크기 및 위치 조정 필요
- 또한 배경 제거를 위한 jpg -> png 변환 필요

**Comment by Eeap** [comment]
로고의 확장자를 바꿀 예정이면 src/views/login/index.vue에 로그인 뷰에서 해당 이미지를 쓰고 있어서 만약 login 기능이 먼저 merge되면 수정 부탁드려요^,,
