### ISSUE TITLE
[기능] 기본 노드 기능 완성

### ISSUE THREAD

**Issue by FacerAin** [Terraform-Canvas/front-end#21]
## 🚀 Feature Request
- **기본 노드들의 기능 (입력 필드, 부모 관계) 완성**하기
- 아래 노드들의 기능 제공 예정
  - Auto Scailing Group
  - VPC
  - AWS DB Instance
  - EC2
  - AWS Security Group
  - ALB & NLB
  - Lambda
  - S3 Bucket
  - Cloudfront

**Comment by Eeap** [comment]
노드들의 복잡한 부모 관계로 데이터를 주고 받기보단 추후에 상태 관리를 한곳에 하면 좋을 것 같아요 :)

**Comment by FacerAin** [comment]
저도 동의합니다! 부모 관계를 어떻게 전역적인 상태로 관리할 수 있을지도 계속 고민해볼게요 😊
