### ISSUE TITLE
[버그] 노드 중첩 시 자식 노드 위치 문제

### ISSUE THREAD

**Issue by FacerAin** [Terraform-Canvas/front-end#30]
## 🚀 Feature Request
- 현재 노드를 중첩시키면 자식 노드의 위치가 튕기는 현상이 있음
- 더불어 다시 한번 끌어 놓으면 정상 동작함.
![image](https://github.com/Terraform-Canvas/front-end/assets/16442978/89f6fec9-e46d-4a71-a139-315277d12e81)

**Comment by FacerAin** [comment]
자식 노드를 한번 더 클릭하면 부모 노드의 위치가 맞게 확장됨.
component referesh나 event listner 쪽의 문제가 아닐까 추측중

**Comment by Eeap** [comment]
사이즈 조절도 안되는 것 같아요. 노드를 넣어서 양옆으로 움직여야 부모노드가 늘어나고 그 이외는 안늘어나요ㅠㅠ

**Comment by FacerAin** [comment]
NodeResizer css 수정 시 **사이즈 조절**이 동작하지 않는 문제는 `line-style="visable: hidden";`에서 `line-style="opacity: 0;"`으로 변경하여 **해결 완료**하였습니다. 
상단 자식 노드 위치 문제도 함께 해결하여 PR 올리도록 하겠습니다 🔥
