### ISSUE TITLE
[수정] DrawerInput props mutation

### ISSUE THREAD

**Issue by FacerAin** [Terraform-Canvas/front-end#48]
## 🚀 Feature Request
- DrawerInput에서 `v-model="selectedNode.data.min_size"` 처럼 props으로 전달 받은 부모 컴포넌트의 데이터를 직접적으로 수정하고 있음
-  Vue3에서 양방향 데이터 전달은 권장하는 패턴이 아니며, `@emit`등을 활용한 처리 필요

## 📎 Additional context
- https://yamyam-naengmyeon-donkats.tistory.com/118

**Comment by Eeap** [comment]
아니면 컴포넌트 데이터를 store로 전역 관리 하는것도 나쁘진 않을 것 같은데

**Comment by Eeap** [comment]
> 아니면 컴포넌트 데이터를 store로 전역 관리 하는것도 나쁘진 않을 것 같은데

근데 여기서 이제 초기화 작업 같은건 잘해줘야할것 같아
